[project]
name = "symmetrical-enigma"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "cookiecutter>=2.6.0",
    "ghp-import>=2.1.0",
    "jupyter-book>=1.0.4.post1",
]
